services:
  #MySQL Database for Job Microservice
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: jobms
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped

  zipkin:
    image:  openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672










#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
  mysql: