CREATE DATABASE IF NOT EXISTS jobms;
CREATE DATABASE IF NOT EXISTS companyms;
CREATE DATABASE IF NOT EXISTS reviewms;

GRANT ALL PRIVILEGES ON jobms.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON companyms.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON reviewms.* TO 'root'@'%';
FLUSH PRIVILEGES;
